2022-01-04 15:06:36,995 INFO: Microblog startup [in /home/nitesh/microblog/app/__init__.py:51]
2022-01-04 15:07:05,016 ERROR: Exception on /edit_profile [POST] [in /home/nitesh/microblog/microblogvenv/lib/python3.6/site-packages/flask/app.py:1458]
Traceback (most recent call last):
  File "/home/nitesh/microblog/microblogvenv/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1803, in _execute_context
    cursor, statement, parameters, context
  File "/home/nitesh/microblog/microblogvenv/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 732, in do_execute
    cursor.execute(statement, parameters)
sqlite3.IntegrityError: UNIQUE constraint failed: user.username

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/nitesh/microblog/microblogvenv/lib/python3.6/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/nitesh/microblog/microblogvenv/lib/python3.6/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/nitesh/microblog/microblogvenv/lib/python3.6/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/nitesh/microblog/microblogvenv/lib/python3.6/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/nitesh/microblog/microblogvenv/lib/python3.6/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/home/nitesh/microblog/app/routes.py", line 111, in edit_profile
    db.session.commit()
  File "<string>", line 2, in commit
  File "/home/nitesh/microblog/microblogvenv/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 1431, in commit
    self._transaction.commit(_to_root=self.future)
  File "/home/nitesh/microblog/microblogvenv/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 829, in commit
    self._prepare_impl()
  File "/home/nitesh/microblog/microblogvenv/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 808, in _prepare_impl
    self.session.flush()
  File "/home/nitesh/microblog/microblogvenv/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 3363, in flush
    self._flush(objects)
  File "/home/nitesh/microblog/microblogvenv/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 3503, in _flush
    transaction.rollback(_capture_exception=True)
  File "/home/nitesh/microblog/microblogvenv/lib/python3.6/site-packages/sqlalchemy/util/langhelpers.py", line 72, in __exit__
    with_traceback=exc_tb,
  File "/home/nitesh/microblog/microblogvenv/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
    raise exception
  File "/home/nitesh/microblog/microblogvenv/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 3463, in _flush
    flush_context.execute()
  File "/home/nitesh/microblog/microblogvenv/lib/python3.6/site-packages/sqlalchemy/orm/unitofwork.py", line 456, in execute
    rec.execute(self)
  File "/home/nitesh/microblog/microblogvenv/lib/python3.6/site-packages/sqlalchemy/orm/unitofwork.py", line 633, in execute
    uow,
  File "/home/nitesh/microblog/microblogvenv/lib/python3.6/site-packages/sqlalchemy/orm/persistence.py", line 241, in save_obj
    update,
  File "/home/nitesh/microblog/microblogvenv/lib/python3.6/site-packages/sqlalchemy/orm/persistence.py", line 1001, in _emit_update_statements
    statement, multiparams, execution_options=execution_options
  File "/home/nitesh/microblog/microblogvenv/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1614, in _execute_20
    return meth(self, args_10style, kwargs_10style, execution_options)
  File "/home/nitesh/microblog/microblogvenv/lib/python3.6/site-packages/sqlalchemy/sql/elements.py", line 326, in _execute_on_connection
    self, multiparams, params, execution_options
  File "/home/nitesh/microblog/microblogvenv/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1491, in _execute_clauseelement
    cache_hit=cache_hit,
  File "/home/nitesh/microblog/microblogvenv/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1846, in _execute_context
    e, statement, parameters, cursor, context
  File "/home/nitesh/microblog/microblogvenv/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 2027, in _handle_dbapi_exception
    sqlalchemy_exception, with_traceback=exc_info[2], from_=e
  File "/home/nitesh/microblog/microblogvenv/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
    raise exception
  File "/home/nitesh/microblog/microblogvenv/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1803, in _execute_context
    cursor, statement, parameters, context
  File "/home/nitesh/microblog/microblogvenv/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 732, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.IntegrityError: (sqlite3.IntegrityError) UNIQUE constraint failed: user.username
[SQL: UPDATE user SET username=?, about_me=? WHERE user.id = ?]
[parameters: ('nitesh2', "Welcome to my blog!Pay attention to the clever conditional I'm using to make sure that the Edit link appears when you are viewing your own p", 1)]
(Background on this error at: https://sqlalche.me/e/14/gkpj)
2022-01-04 15:17:01,009 INFO: Microblog startup [in /home/nitesh/microblog/app/__init__.py:51]
